### ISSUE TITLE
[Feat] 지출 기록 조회 기능

### ISSUE THREAD

**Issue by CheorHyeon** [CheorHyeon/MoneyWay#16]
## 📝 개요
- 지출 기능 조회 기능을 구현합니다.
- 본인이 작성한 내역만 조회가 가능합니다.

## ✅ TO-DO
- [x] 지출 내역 조회(목록)
  - [x] 기간별 조회
  - [x] 지출 합계 / 카테고리별 지출 합계 (합계제외 처리)
  - [x] 특정 카테고리만 조회
  - [x] 최소, 최대 금액으로 조회
- [x] 지출 내역 조회(상세)

## 📌 ETC
-
