### ISSUE TITLE
[Feat] 예산 설정 API, 예산 설계(추천) API

### ISSUE THREAD

**Issue by CheorHyeon** [CheorHyeon/MoneyWay#9]
## 📝 개요
- 카테고리별 예산 설정API를 구현합니다.
- 총액을 입력받아 카테고리별 예산 추천 API를 구현합니다.

## ✅ TO-DO
- [x] 카테고리별 예산 설정 더미데이터 생성(추천에 사용되기 위함)
- [x] 카테고리별 예산을 입력 받아 설정 API
- [x] 카테고리별 예산 추천 API

## 📌 ETC
-
